### ISSUE TITLE
[SUGGESTION] Team up with pipiche38 who is developing a zigpy plugin for Domoticz 

### ISSUE THREAD

**Issue by Hedda** [grobasoz/zigbee-hardware#1]
@grobasoz Can I suggest that you try to reach out to @pipiche38 (Patrick Pichon) about possible collaborating and teaming up to test your new Zigbee hardware with the new Zigbee implementation for Domoticz that he is developing using [zigpy](https://github.com/zigpy/zigpy)?

* https://github.com/pipiche38/Domoticz-Zigpy/

Read in zigpy/bellows#243 that you have USB dongles that you will soon start ready sell and Domoticz support would be nice.

Please also see respective suggested posted to pipiche38 here:

https://github.com/pipiche38/Domoticz-Zigpy/issues/4

If you could donate one, two, or a few of your Silicon Labs ERF32 based Zigbee hardware (USB dongles or Raspberry Pi Shields) to him then maybe he that can help @pipiche38 developing effort as it would give him the possibility to also test the [bellows](https://github.com/zigpy/bellows) radio libraries for [zigpy](https://github.com/zigpy/zigpy) to try out their compatibility with Silabs EFR32 Mighty Gecko based Zigbee adapters as zigpy can support many different adapters. Your hardware adapters could perhaps later even be used as reference hardware. No strings attached of course as these are still hobby projects at their core with only one developer so far. 

https://github.com/zigpy/zigpy

https://github.com/zigpy/bellows

Please understand that pipiche38 is still in a very early stage of developing his "Domoticz-Zigpy" plugin for [Domoticz](https://www.domoticz.com) (a free and open-source home automation software), I understand in fact the project is so a such early in development that is not yet usable, however, I read on Domoticz community forum that he currently only has access to ZiGate Zigbee adapters (this as pipiche38 is also the developer of an existing ZiGate plugin for Domoticz). So at least we know that pipiche38 already has the experience and skills to develop Zigbee plugins for Domoticz.

* https://github.com/pipiche38/Domoticz-Zigate-Wiki/blob/master/en-eng/Home.md

* https://www.domoticz.com/wiki/Zigate

I believe that grobasoz zigbee hardware, zigpy, Domoticz, and this new "Domoticz-Zigpy" plugin are all only spare-time hobby projects at this point, but still, I think that teaming up might give all involved projects some positive recognition in the Domoticz community and the whole home automation scene in general which might attract more developers and willing alpha/beta-testers from the community to come to help out with all these involved projects which in the long run could benefit all users wanting Zigbee in Domoticz to become more mature and working with more Zigbee hardware dongles than it is today.

**Comment by grobasoz** [comment]
@Hedda - sure, happy to donate when ready. Looking at a couple weeks before I can ship a sample though...

**Comment by Hedda** [comment]
@grobasoz That is great to hear! Can you pre-flash with Silabs EmberZNet firmware versions compatible with bellows library?

As discussed in https://github.com/zigpy/bellows/issues/243

Right now the master version of bellows is only compatible with EZSP v4 but latest dev branch is compatible up to EZSP v8.

PS: Elelabs EZSP Firmware Update Utility allow you to change EZSP protocol version between EZSP v6 and v8 in newer firmware:

https://github.com/Elelabs/elelabs-zigbee-ezsp-utility

 As I understand it, the very latest EmberZNet application firmware is only backwards-compatible back to EZSP v6? 

Some version of EmberZNet application firmware before that supported EZSP v4 up to EZSP  v7 (but did not support EZSP v8)?

**Comment by grobasoz** [comment]
@Hedda - With EZSP V8, the frame header changed (frame control to 2 bytes) so previous "host" versions couldn't be used. 
In most cases, the Silabs generated host application would check the NCP firmware version for compatibility. 

The latest EmberZNet created host will only work with V8 based NCP firmware. 

Since a standalone bootloader is used, any version of EZSP can be programmed over the UART interface using XModem. 

I have factory installed NCP (115k2 Baud, SW flow control) V8 on my current batch of Zigbee modules as a standard.

**Comment by Hedda** [comment]
> I have factory installed NCP (115k2 Baud, SW flow control) V8 on my current batch of Zigbee modules as a standard.

@grobasoz That's good! So current default settings in ZHA work 'out-of-the-box' https://www.home-assistant.io/integrations/zha/


> Since a standalone bootloader is used, any version of EZSP can be programmed over the UART interface using XModem.

Cool! That should then also work with Elelabs EZSP Firmware Update Utility https://github.com/Elelabs/elelabs-zigbee-ezsp-utility
