### ISSUE TITLE
[REQUEST] Texas Instruments CC1352P based gateway/bridge or USB-adapter/stick/dongle with support for Sub-1 GHz frequencies

### ISSUE THREAD

**Issue by Hedda** [grobasoz/zigbee-hardware#2]
Any chance would consider making a Texas Instruments CC1352P based gateway/bridge or USB-stick/dongle hardware adapter?

The reason is that CC1352 supports all Zigbee radio frequencies so could be made to work with Zigbee Smart Energy (ZSE).

CC1352 is more expensive but enable Sub-1 GHz frequencies used by Zigbee Smart Energy (SE) profile not part of Zigbee 3.0

https://www.ebyte.com/en/product-view-news.aspx?id=766

https://www.szrfstar.com/product/235-en.html

https://www.szrfstar.com/product/188-en.html

Zigbee Smart Energy is the world standard used by electricity, water, and gas meters that all utility companies install in your house.

As far as I know niether zigpy or zigbee-herdsman (zigbee2mqtt and iobroker) support the Zigbee SE profile as of yet.

Having CC1352 hardware available would allow developers to add support to zigpy and zigbee-herdsman (zigbee2mqtt/iobroker).

https://zigbeealliance.org/solution/smart-energy/

https://zigbeealliance.org/wp-content/uploads/2019/11/docs-07-5356-19-0zse-zigbee-smart-energy-profile-specification.pdf

https://training.ti.com/overview-zigbee-smart-energy-internet-things

https://www.ti.com/lit/slaa467

https://www.ti.com/lit/pdf/tidu213

https://www.ti.com/lit/pdf/swra467

https://www.nxp.com/pages/jn516x-zigbee-smart-energy:ZIGBEE-SMART-ENERGY

https://www.nxp.com/docs/en/supporting-information/MAXSECZBNETART.pdf

"Zigbee Smart Energy (Zigbee SE) is the world's leading standard for interoperable wireless products that monitor, control and automate the delivery and use of energy (and other resources, such as water). A wireless network is implemented at the consumer's premises using the ZigBee PRO protocol with the Smart Energy application profile. This Home Area Network (HAN) contains devices such as a Metering Device, In-Premise Display (IPD) and Load Control Device, and is connected to the energy provider using an Energy Service Interface (ESI) via a backhaul network."

PS: ZOE2 shield/hat by Electrorama will use CC1352P radio from Texas Instruments, using the E79-400DM2005S module by EByte:

https://electrolama.com/projects/zoe2/

https://github.com/electrolama/zoe2

**Comment by Hedda** [comment]
It should let you get metrics from your house smart electricity meter, water meter, and gas meter if they use unencrypted Zigbee SE.

It provide data on your house energy/water/gas usage for your homes utilities, which is something many home automation users want.

That is, Zigbee SE is not normally used in devices that consumer buy themselves but it is not only used in industries or commercial housing but for normal residential homes in devices that your utility companies install in your house on monitor your each house utility usage. If they install it then they can usually for transparency offer to allow read-only access so that you can get data on your own usage.

Example of a consumer-level device that uses Zigbee SE: 

https://www.rainforestautomation.com/rfa-z114-eagle-200-2/

Zigbee SE is a similar concept but not the standard same as H1/P1 protocol which is accessed via wired RJ45 HAN (Home Area Network) port on same type of new energy meters in Europe. Many of those support both Zigbee SE for wireless and HAN for wired.

https://blog.sintef.com/sintefenergy/han-port-smart-meters-ams/

https://www.kode24.no/guider/smart-meter-part-1-getting-the-meter-data/71287300

PS: I myself have a wired HAN-adapter connected to a Kamstrup electricity meter that my utility company installed in my house.It should let you get metrics from your house smart electricity meter, water meter, and gas meter if they use unencrypted Zigbee SE.

It provides data on your house energy/water/gas usage for your home's utilities, which is something many home automation users want. Even if you are only sniffing Zigbee Smart Energy signals to pick up readings from your utilities smart meter(s).

That is, Zigbee SE is not normally used in devices that consumer buy themselves but it is not only used in industries or commercial housing but for normal residential homes in devices that your utility companies install in your house on monitor your each house utility usage. If they install it then they can usually for transparency offer to allow read-only access so that you can get data on your own usage.

Example of a consumer-level devices that uses Zigbee SE: 

https://www.rainforestautomation.com/rfa-z114-eagle-200-2/
https://zigbeealliance.org/zigbee_products/emerson-smart-thermostat-2/
https://zigbeealliance.org/zigbee_products/emerson-smart-thermostat/
https://zigbeealliance.org/zigbee_products/foundation-fz100-smart-thermostat/

Example of Zigbee Smart Energy Metering device that your utility company would install to monitor usage in your house:

https://zigbeealliance.org/zigbee_products/kamstrup-electricity-meter-se/
https://zigbeealliance.org/zigbee_products/0003-14/
https://zigbeealliance.org/zigbee_products/0003-10/
https://zigbeealliance.org/zigbee_products/0005-4/
https://zigbeealliance.org/zigbee_products/series-6-s4x/
https://zigbeealliance.org/zigbee_products/sensus-stratus-iq-meter/
https://zigbeealliance.org/zigbee_products/atlas-mk7a-energy-meter/
https://www.smart-energy.com/regional-news/europe-uk/first-zigbee-enabled-heat-meter-launched-by-kamstrup/
https://www.develcoproducts.com/products/meter-interfaces/kamstrup-meter-interface/
https://www.develcoproducts.com/media/1790/kamstrup-meter-interface-flyer_v14.pdf

Zigbee SE is a similar concept but not the standard same as H1/P1 protocol which is accessed via wired RJ45 HAN (Home Area Network) port on same type of new energy meters in Europe. Many of those support both Zigbee SE for wireless and HAN for wired.

https://blog.sintef.com/sintefenergy/han-port-smart-meters-ams/

https://www.kode24.no/guider/smart-meter-part-1-getting-the-meter-data/71287300

PS: I myself have a wired HAN-adapter connected to a Kamstrup electricity meter that my utility company installed in my house.

**Comment by Hedda** [comment]
Oh, and just to clarify; CC1352 radio has multi-band support which it support both Sub-1 GHz and 2.4GHz frequencies at the same timeOh, to clarify; CC1352P radio has multi-band support meaning it supports both Sub-1 GHz + 2.4GHz frequencies at the same time.

"CC1352P SimpleLink Arm Cortex-M4F multiprotocol Sub-1 GHz & 2.4 GHz wireless MCU integrated power amplifier"

https://www.ti.com/product/CC1352P

**Comment by grobasoz** [comment]
@Hedda - thanks for the consideration. Unfortunately my project schedule is fully allocated for the next few months... Gary.

**Comment by gravypower** [comment]
Stumbled across this issue as I am looking for something similar, how is the project schedule looking now @grobasoz?

**Comment by grobasoz** [comment]
@gravypower - Still busy but probably not going to look at using the TI products any time soon. I prefer to stick with the Silicon Labs based devices as I have all my firmware and radio modules based on them - viz EFR32MG21's and EFR32MG24 later in the year. I'm also not really a fan of USB (or WiFi) based dongles for use in Gateways as many customers have complained about interference and signal loss with both... as a result I currently only develop for and sell Ethernet based Gateways :)

**Comment by gravypower** [comment]
Ultimately I am just looking for a cost effective option to communicate with my smart meter in a small form factor to pipe into a node red flow. I am just unpacking Zigbee Smart Energy Standard 1.1, but could your gateways join a smart meter HAN? Or it needs to be the TI chip? 

Also thanks for your reply.

**Comment by grobasoz** [comment]
My last attempts at ZSE were confounded by the need to get an ECC certificate? The Gateway should be able to support SE with modified firmware...

**Comment by gravypower** [comment]
so i guess my next question is where can I get a hold of your gateway? :)

**Comment by Hedda** [comment]
> Ultimately I am just looking for a cost effective option to communicate with my smart meter in a small form factor to pipe into a node red flow. I am just unpacking Zigbee Smart Energy Standard 1.1, but could your gateways join a smart meter HAN?

If you are not specifically looking to hack a DIY gateway/reader then you would probably be better off just looking if you can find a specialised "CAD" ("Consumer Access Device") product which is made to be a consumer Zigbee HAN reader designed to evesdrop in order to capture and decode Zigbee Smart Energy 2.0 and provide a consumer interface (and sometimes also an API), see ex:

https://community.openenergymonitor.org/t/electricity-meters-with-han-interface/11813

https://www.rainforestautomation.com/rfa-z114-eagle-200-2/

https://geotogether.com/business/products-services/smart-energy/

Alternativly research how to build your own  Zigbee HAN packet analyser for SMETS meters (SMETS1 and/or SMETS2 meter?)?

https://shkspr.mobi/blog/2020/04/hacking-your-smart-meter-part-1-zigbee/

https://www.reddit.com/r/homeassistant/comments/b65pdr/smart_utility_meters_zigbee/

https://forum.ovoenergy.com/smart-meters-136/can-i-use-a-zigbee-han-packet-analyser-to-help-identify-my-smart-meter-in-home-display-ihd-issues-my-current-supplier-can-t-help-9843

At least I understand Zigbee SE devices can not join a Zigbee 3.0 network because those stacks use different security encryption(?) as Zigbee Smart Energy does not use a Zigbee 3.0 network but instead a "Zigbee Smart Energy Home Area Network" (e.i. "HAN").

I believe instead the standard Zigbee SDK from Silicon Labs is primarly only designed for Zigbee 3.0 which includes the Zigbee PRO specification but does not include support for Zigbee Smart Energy (ZSE), so for that so you need a other custom firmware.

https://community.silabs.com/s/article/what-is-zigbee-3-0?language=en_US

https://www.silabs.com/documents/public/white-papers/ZigBee-based-HANs-for-Energy-Management.pdf

https://zigbeealliance.org/wp-content/uploads/2019/11/docs-07-5356-19-0zse-zigbee-smart-energy-profile-specification.pdf

https://www.silabs.com/documents/public/white-papers/zigbee-propagation-for-smart-metering.pdf

https://www.silabs.com/documents/public/application-notes/an714-smart-energy-ecc-enabled-device-setup.pdf

https://www.silabs.com/documents/public/application-notes/an1233-zigbee-security.pdf

I think the same goes for Texas Instruments as well which also has a different Zigbee SDK / Zigbee stack for Zigbee Smart Energy.

https://training.ti.com/zigbee-smart-energy-home-area-network-internet-things

https://training.ti.com/zigbee-smart-energy-profile-20-demo

PS: As mentioned in openenergymonitor.org community forum thread it is likley that commercial Zigbee Smart Energy meters do not use 2,4GHz but instead uses a Sub-1GHz Zigbee radio (like ex. 868MHz in Europe or 920MHz in  USA) to get greater range:

**Comment by grobasoz** [comment]
@gravypower - My Gateway wouldn't be of any use to you as it doesn't support Smart Energy. I just use it as an interface to a standard Home Automation system, eg Home Assistant. As mentioned by Hedda in his excellent response (thanks @Hedda), the [RainForest Eagle ](https://www.rainforestautomation.com/rfa-z114-eagle-200-2/)is a great place to start - if your smart meter is supported by it...

**Comment by MattWestb** [comment]
Sirlabs GSDK you is getting access with the "well known link key" so you can using the cooked device with Zigbee HA and ZB3. You can cooking ZLL devices but you dont getting the ZLL master key and must requesting it and writing on agreement for getting it and not giving it to "Valdermir".
The same is for ZSE you need baying and requesting for getting the SDK access and the extended encryption being used in ZSE that is not in the standard GSDK and can not being exporter to Vladermir and Co.
